### ISSUE TITLE
Create a Simple Multi-Page Application Demo

### ISSUE THREAD

**Issue by broepke** [mkhorasani/Streamlit-Authenticator-demo#1]
Hi there - I'm trying to get your latest updates working with a multi-page application.  I would love it if you created a super simple one that would highlight how to use the session state properly:

> _Please remember to pass the authenticator object to each and every page in a multi-page application as a session state variable._

and

> _Please remember to re-invoke an 'unrendered' login widget on each and every page in a multi-page application._

I started to rough one out here: [https://github.com/broepke/streamlit-auth-test-app](https://github.com/broepke/streamlit-auth-test-app)

**Comment by broepke** [comment]
Note - I got it mostly working - it seems about right - however, I'd love for you to review it and tell me if I'm doing this right or if there are suggestions.

**Comment by mkhorasani** [comment]
Hey @broepke, I took a quick glance and it looks fine!

**Comment by broepke** [comment]
Thank you @mkhorasani.  Feel free to steal that as a base line if you want to put up another sample app like your all in one single page!
